version: '3.4'
services:

  postgres:
    container_name: postgres-postgis
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_db
    ports:
      - "5432:5432"
    networks:
      - local

networks:
  local:
    driver: bridge
